version: '3.5'

services:
  backend:
    working_dir: /app
    restart: always
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    links:
      - db:${MYSQL_HOST}
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/backend/src
      - ./core/src:/app/core/src
      - ./storage:/app/storage
    ports:
      - "4000"
    networks:
      - appnetwork
    tty: true
    stdin_open: true
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file: .env
  db:
    image: mysql:latest
    restart: always
    container_name: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    env_file: .env
    networks:
      - appnetwork
  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - VUE_APP_BASE_APP_URL=${VUE_APP_BASE_APP_URL}
    stdin_open: true
    tty: true
    env_file: .env
    networks:
      - appnetwork
networks:
  appnetwork:
    driver: bridge
volumes:
  mysql_data:
  storage: