version: '3.5'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: production
    command: 'npm run start:prod:backend'
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: production
    volumes:
      - ./storage:/var/www/html/storage/
      - /etc/letsencrypt:/etc/letsencrypt
      - ./docker/nginx/config/:/etc/nginx/config
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"